version: "3"
services:
  redis:
    image: redis:alpine
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=nucleus
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    env_file:
      - ./nucleus.env
  web:
    image: nucleus:local
    ports:
      - "8000:8000"
    links:
      - redis
      - db
    env_file:
      - ./nucleus.env
    command: daphne -b 0.0.0.0 -p 8000 nucleus.asgi:channel_layer
  worker:
    image: nucleus:local
    links:
      - redis
      - db
    env_file:
      - ./nucleus.env
    command: python3 manage.py runworker

