version: "3"
services:
  docker:
    image: docker:dind
    privileged: true
  redis:
    image: redis:alpine
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=nucleus
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    env_file:
      - ./nucleus.env
  web:
    image: nucleus:local
    links:
      - db
      - redis
    ports:
      - "8000:8000"
    env_file:
      - ./nucleus.env
    command: daphne -b 0.0.0.0 -p 8000 nucleus.asgi:channel_layer
  worker:
    image: nucleus:local
    links:
      - db
      - redis
      - docker
    env_file:
      - ./nucleus.env
    command: bash -c 'export DOCKER_HOST=tcp://docker:2375; sleep 20; python3 manage.py runworker'

