version: "3"
services:
  docker:
    image: docker:dind
    privileged: true
  redis:
    image: redis:alpine
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=nucleus
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    env_file:
      - ./nucleus.env
  web:
    image: registry.gitlab.com/devine-industries/nucleus:latest
    links:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      - NUCLEUS_DB_HOST=db
      - NUCLEUS_DB_PORT=3306
      - NUCLEUS_REDIS_HOST=redis
      - NUCLEUS_REDIS_PORT=6379
    env_file:
      - ./nucleus.env
    command: daphne -b 0.0.0.0 -p 8000 nucleus.asgi:channel_layer
  worker:
    image: registry.gitlab.com/devine-industries/nucleus:latest
    links:
      - db
      - redis
      - docker
    environment:
      - NUCLEUS_DB_HOST=db
      - NUCLEUS_DB_PORT=3306
      - NUCLEUS_REDIS_HOST=redis
      - NUCLEUS_REDIS_PORT=6379
    env_file:
      - ./nucleus.env
    command: bash -c 'export DOCKER_HOST=tcp://docker:2375; sleep 20; python3 manage.py runworker --exclude-channels=http.*'
  http_worker:
    image: registry.gitlab.com/devine-industries/nucleus:latest
    links:
      - db
      - redis
    environment:
      - NUCLEUS_DB_HOST=db
      - NUCLEUS_DB_PORT=3306
      - NUCLEUS_REDIS_HOST=redis
      - NUCLEUS_REDIS_PORT=6379
    env_file:
      - ./nucleus.env
    command: bash -c 'sleep 20; python3 manage.py runworker --include-channels=http.*'

